[RFC] WEB: Modernize the data model
scummvm/scummvm-web pull request #131
Opened 2020-09-12 04:36 UTC by Mataniko

This PR updates the current data model and moves most data into a database-like structure.

For example, versions are no longer read from filenames, various names for games, companies and engines now pull from their respective data files and cross referenced.

The first page that this can be seen is in the compatibility page, where we now have a much simpler format for compatibility data (see compatibility.yaml) where we only need to enter the deltas between versions, and not copy the entire file again. By having more structured data, we now auto generate most of the game notes - leaving devs to only add pertinent information.

Once other pages are updated (demos, screenshots) we will also have consistency in naming across pages.

There's more work to do before merging this: safety checks, missing data validation, bug squashing, naming and general data correction - but as of now the site is runnable with the new model. 

I encourage you to try it out, and suggest improvements and corrections.

2020-09-13 15:41 UTC, Mataniko commented
With the latest commit, I think this should be good to merge.

2020-09-14 02:05 UTC, Mataniko commented
Taking back what I said - I added a script to pull data directly from the spreadsheet and into the site - so updates will not require manually updating yaml files. Instead all work can be done in sheets, as a visual database.

2020-09-15 04:37 UTC, Thunderforge requested changes
Despite my many comments (inevitable due to the number of files, I presume), I'm very impressed with this effort. Great work!

Most of my comments were related to documentation; I had a bit of confusion as a reviewer about the purpose of some things, and I assume that future maintainers who want to make changes will too. Fortunately, they should be easy to address. I didn't really have any technical concerns aside from handling of `DEV` versions.

Looking forward to seeing this merged!

2020-09-15 04:37 UTC, Thunderforge commented on data/platforms.yaml
> +  name: Macintosh
I suggest "Classic Mac OS" because that's [the name used by Wikipedia](https://en.wikipedia.org/wiki/Classic_Mac_OS). Similarly, the id would be `classic-macos`. This would avoid any potential confusion with "Modern" macOS, both of which are sometimes informally called "Macintosh".

2020-09-15 04:37 UTC, Thunderforge commented on data/series.yaml
> +  name: Indian Jones
Should be Indiana Jones.

2020-09-15 04:37 UTC, Thunderforge commented on data/companies.yaml
> +  alt_name: ""
I assume that the `""` is necessary if it's blank? I would prefer omitting it if it's optional, since quotes aren't used elsewhere.

2020-09-15 04:37 UTC, Thunderforge commented on data/companies.yaml
> +- id: ""
Why do these have no id? Did we just not get around to giving one?

2020-09-15 04:37 UTC, Thunderforge commented on data/compatibility.yaml
> +  notes: '- Minor graphical glitches in NES version'
I think we can get rid of the leading `- `.

2020-09-15 04:37 UTC, Thunderforge commented on data/compatibility.yaml
> +  unstable_platforms: ""
I like that we have stable and unstable platforms separated.

2020-09-15 04:37 UTC, Thunderforge commented on data/compatibility.yaml
> +  version: 2.0.0
What does `version` mean here? The version of the game? The version of ScummVM it was first supported in?

Assuming it's the first version that ScummVM supported it, I think it would be better to have this property called `since_version` instead.

2020-09-15 04:37 UTC, Thunderforge commented on data/compatibility.yaml
> +  notes: '- There is no support for the Macintosh interface - FM-TOWNS Kanji version
I don't know that this "bullet points" works well in a string. It would be good to have some other structure. Maybe a YAML list?

```yaml
notes:
    - There is no support for the Macintosh interface
    - FM-TOWNS Kanji version
```
This would also avoid the issue of a leading `–`.

2020-09-15 04:37 UTC, Thunderforge commented on data/compatibility.yaml
> +  support: good
I'm still of the opinion that "support" is a useless metric since they all are either "Good" or "Excellent" and we can't seem to agree on what the difference is between them, but I'm willing to fight that battle another day and not let it hold up this review.

2020-09-15 04:37 UTC, Thunderforge commented on data/compatibility.yaml
> +    from original interpreter.\'
Trailing `\` should be removed.

2020-09-15 04:37 UTC, Thunderforge commented on public_html/index.php
> + * Development only - when using PHP built in web server
And what does this do that we only want it to happen when run in development? A comment explaining the functionality would be helpful.

2020-09-15 04:37 UTC, Thunderforge commented on include/Pages/CompatibilityPage.php
> +        $compareVersion = $version === 'DEV' ? '9.9.9' : $version;
If we ever changed our versioning scheme (such to Chrome-style where we increase the full version each release and get up to like version 75) this will break. Or if we just keep this code long enough that we do see ScummVM 9.10.0. I would prefer a solution that is more robust for that, but I won't hold up the PR for it.

2020-09-15 04:37 UTC, Thunderforge commented on include/Objects/LegacyCompatGame.php
> + * The LegacyCompatGame class represents a game on the compatibility charts on the
I assume that `Legacy` in the name refers to the class being legacy in contrast to a new `CompatGame` class? It would be good to add the new replacement in the comments.

2020-09-15 04:37 UTC, Thunderforge commented on include/Objects/Engine.php
> + * The Engine object represents a game engine supported by ScummVM
Are they all supported? I thought there were a few WIP engines included. If they are indeed only supported engines, then ignore this comment.

2020-09-15 04:37 UTC, Thunderforge commented on include/Objects/Game.php
> + * The Game object represents a game known to ScummVM
This is analogous to the Engine class, but that one says it's supported engines while this just says it's "known to", meaning they can be supported or unsupported. It would be good to clarify (and be consistent if possible).

2020-09-15 04:37 UTC, Thunderforge commented on include/Objects/Compatibility.php
> +            $notes .= str_replace("- ", "\n- ", $this->notes) . "\n";
This is temporary, right? It seems that it would be better to long-term format the data so that such conversions are unnecessary.

2020-09-15 04:37 UTC, Thunderforge commented on include/Objects/Compatibility.php
> + * The Compatibilith object represents a game on the compatibility charts on the
Typo: `Compatibilith` → `Compatibility`.

2020-09-15 04:37 UTC, Thunderforge commented on include/Objects/Company.php
> + * The Company object represents a companies that created games supported
`represents a companies` → `represents the companies`.

2020-09-15 04:37 UTC, Thunderforge commented on include/Models/VersionsModel.php
> +            $data['DEV'] = new Version(["id" => 'DEV', "date" => "1/1/2099"]);
I assume this is necessary to keep other things from breaking; I'm in favor of instead handling undefined data specially instead of creating arbitrarily large values, but I won't hold the PR up over it.

2020-09-15 04:37 UTC, Thunderforge commented on include/Models/LegacyCompatibilityModel.php
> +    const NO_VERSION = 'No version specified.';
See, this seems like a better way to handle things than versions of `9.9.9`.

2020-09-15 04:37 UTC, Thunderforge commented on include/Models/CompaniesModel.php
> + * The CompanysModel is used to cross reference companyies across the website
Typo: `companyies` → `companies`

2020-09-15 04:37 UTC, Thunderforge commented on include/DataUtils.php
> +class DataUtils
I think a comment should be added explaining this class in detail, given that it generates the data that powers so much of this website.

2020-09-15 04:37 UTC, Thunderforge commented on data/versions.yaml
> +# This is a generated file, please do not edit manually
My preferred name for the file would; be `scummvm_versions.yaml` to clarify that it's for the app, not for any of the supported games.

2020-09-15 04:37 UTC, Thunderforge commented on data/versions.yaml
> +  date: 12/1/2002
I would prefer that dates be in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. ScummVM has a global audience, and we shouldn't be storing in dates that could be confused by readers from different parts of the globe (is this December 1st or January 12th)?

2020-09-15 04:37 UTC, Thunderforge commented on data/versions.yaml
> +  name: ""
It looks like all releases have this field blank. What's the purpose of this?

2020-09-15 04:37 UTC, Thunderforge commented on data/games.yaml
> +  moby_id: "222"
Why does the `moby_id` need quotes if other fields don't? It seems redundant and I would prefer to remove them if we can.

2020-09-15 04:37 UTC, Thunderforge commented on data/games.yaml
> +  name: 'Amazon: Guardians of Eden'
These single-quotes should be removed; Martian Memorandum above doesn't have them, so I assume they're optional.

2020-09-15 04:37 UTC, Thunderforge commented on data/games.yaml
> +  name: 'Dráscula: The Vampire Strikes Back'
I assume it has been verified that this will display properly; we had an issue a while back where non-ASCII characters weren't.

2020-09-15 15:46 UTC, Mataniko commented on data/platforms.yaml
> +  enum: kPlatform3DO
I used it to map to a data dump of stable/unstable entries - it should just be removed in the data

2020-09-15 15:48 UTC, Mataniko commented on data/platforms.yaml
> +  name: Macintosh
I don't feel strongly about it either way - but i think this matches better on what's on the actual game boxes that people look at, or how these games are historically referred to

2020-09-15 15:50 UTC, Mataniko commented on data/companies.yaml
> +  alt_name: ""
That's how PHP yaml emit works.

2020-09-15 15:51 UTC, Mataniko commented on data/companies.yaml
> +- id: ""
this is outdated, data has been fixed upstream

2020-09-15 15:51 UTC, Mataniko commented on data/compatibility.yaml
> +  notes: '- Minor graphical glitches in NES version'
markdown bullet list

2020-09-15 15:52 UTC, Mataniko commented on data/compatibility.yaml
> +  notes: '- There is no support for the Macintosh interface - FM-TOWNS Kanji version
That's impossible to represent in tabular data

2020-09-15 15:52 UTC, Mataniko commented on data/compatibility.yaml
> +  version: 2.0.0
i had it originally as from_version - i agree

2020-09-15 15:53 UTC, Mataniko commented on data/compatibility.yaml
> +  version: 2.0.0
The only issue is that everything at 2.0.0 is not "since version" 2.0.0. This field is more "relevant for version XXX and up"

2020-09-15 15:54 UTC, Mataniko commented on include/Pages/CompatibilityPage.php
> +        $compareVersion = $version === 'DEV' ? '9.9.9' : $version;
Hasn't happened in 20 years, and if it ever does happen - we can fix this.

2020-09-15 15:56 UTC, Mataniko commented on include/Models/LegacyCompatibilityModel.php
> +    const NO_VERSION = 'No version specified.';
We need to keep DEV because otherwise we'll break URL handling for /DEV

2020-09-15 15:58 UTC, Mataniko commented on data/games.yaml
> +  moby_id: "222"
my guess is pulling the data from sheets everything looks like a string so it gets parsed to a string - or maybe that was a side effect of having non-numeric values in the column

2020-09-15 15:59 UTC, Mataniko commented
Thanks for the feedback - there's no point in commenting on the YAML files since they are generated - we can't control the exact structure. If there are data errors they should be fixed in the spreadsheet for now and we can refresh the data. 

Can you please resolve the comments where appropriate?

2020-09-15 17:45 UTC, Mataniko commented on data/versions.yaml
> +  date: 12/1/2002
Will eventually do that - we don't use the dates at the moment.__

2020-09-15 17:46 UTC, Mataniko commented on data/games.yaml
> +  name: 'Amazon: Guardians of Eden'
It's due to the colon which is a special character

2020-09-15 17:51 UTC, Mataniko commented on data/games.yaml
> +  name: 'Dráscula: The Vampire Strikes Back'
Yes

2020-09-15 17:55 UTC, Mataniko commented on include/Pages/CompatibilityPage.php
> +        $compareVersion = $version === 'DEV' ? '9.9.9' : $version;
(Only reason we assign an actual number to DEV is version comparison)

2020-09-16 00:49 UTC, Thunderforge commented on data/compatibility.yaml
> +  notes: '- Minor graphical glitches in NES version'
Huh, I didn't realize we were putting markdown within a string. If it works, I'll accept it; I had thought it was a holdover from old data.

2020-09-16 00:51 UTC, Thunderforge commented on data/compatibility.yaml
> +  version: 2.0.0
I'm a bit confused about what you're saying here. Can you rephrase what you mean?

My understanding is that we have an entry (`maniac`) and the `2.0.0` means that this is the version it was introduced in, so it's available in this revision and later. Is that not how this works?

2020-09-16 00:53 UTC, Thunderforge commented on data/compatibility.yaml
> +  notes: '- There is no support for the Macintosh interface - FM-TOWNS Kanji version
Since you said earlier that the string is later being parsed as markdown, I'm less concerned about this. I had missed that bit of information.

2020-09-16 00:55 UTC, Thunderforge commented on include/Pages/CompatibilityPage.php
> +        $compareVersion = $version === 'DEV' ? '9.9.9' : $version;
Alright, well like I said, I won't hold up the PR for it if you don't think it's worth fixing.

2020-09-16 00:56 UTC, Thunderforge commented on include/Models/LegacyCompatibilityModel.php
> +    const NO_VERSION = 'No version specified.';
Per other comments: I won't hold up the PR over this, so marking as resolved.

2020-09-16 00:57 UTC, Thunderforge commented on data/versions.yaml
> +  date: 12/1/2002
If the dates aren't being used right now, then it's just a matter of changing them in the spreadsheet? Or do we need to make changes to this code so that if it is changed in the spreadsheet it won't break things?

2020-09-16 01:03 UTC, Thunderforge reviewed
Had a few outstanding items, otherwise I'm glad to see that my concerns were addressed.

2020-09-16 01:03 UTC, Thunderforge commented on data/platforms.yaml
> +  name: Macintosh
@sev- Maybe you can be a tiebreaker here? Should the platform be labeled with the historic name of `Macintosh` or the modern name (as used on Wikipedia) of `Classic Mac OS`?

2020-09-16 01:03 UTC, Thunderforge commented on include/DataUtils.php
> +class DataUtils
Thanks for adding the description.

2020-09-16 01:07 UTC, Mataniko commented on data/compatibility.yaml
> +  version: 2.0.0
I'm not planning to migrate the old compatibility lists to the new format due to the amount of work required with no real value. right now 99% of the list is "since version 2.0.0" which is not the version the game was introduced to scummvm, it's the version the compatibility entry is relevant since

2020-09-16 01:08 UTC, Mataniko commented on data/versions.yaml
> +  date: 12/1/2002
spreadsheet - i recently added support to automatically convert epoch dates to localized date strings, that's the format we should use

2020-09-16 01:09 UTC, Mataniko commented on data/games.yaml
> +  moby_id: "222"
if it ain't broke... they're will be used in HTTP requests, and will have to be casted to a string at that point anyway.

2020-09-16 01:11 UTC, Mataniko commented on data/platforms.yaml
> +  name: Macintosh
We are referring to the computer platform here, not the operating system.

2020-09-16 02:11 UTC, Thunderforge commented on data/compatibility.yaml
> +  version: 2.0.0
So if I understand this correctly then:

* All games have an entry corresponding with version 2.0.0
* Games with changes to their information since 2.0.0 will have another entry (say, 2.1.0) that will include any changes to the original 2.0.0 entry.

Is that correct?

2020-09-16 02:12 UTC, Thunderforge commented on data/versions.yaml
> +  date: 12/1/2002
Okay, glad to hear that it's something that can easily be changed in the spreadsheet without breaking code in this PR.

2020-09-16 02:13 UTC, Thunderforge commented on data/platforms.yaml
> +  name: Macintosh
I'm not sure I understand the distinction. We use operating systems for other entries like DOS, Windows, Linux, and AmigaOS.

2020-09-16 03:56 UTC, Mataniko commented on data/platforms.yaml
> +  name: Macintosh
The nomenclature changed over the years for platforms vs OS. When you bought a game it would say "DOS compatible" or "MS-DOS compatible" or "Macintosh compatible" 

If anything - AmigaOS is the wrong nomenclature.

2020-09-16 04:01 UTC, Mataniko commented on data/compatibility.yaml
> +  version: 2.0.0
More accurately:
All games have an entry, which most of them correspond with 2.0.0 since that's the cutoff for the data conversion
Yes, changes will overwrite previous entries.

2020-09-18 01:43 UTC, Thunderforge commented on data/platforms.yaml
> +  name: Macintosh
I suppose it's something that can be change easily since it's just data and isn't directly related to the code you're merging. I'll resolve the conversation for now so it doesn't hold up merging this code.

2020-09-18 01:43 UTC, Thunderforge approved these changes

2020-09-23 04:18 UTC, Mataniko commented
The last few commits introduce caching to data models.

Today our website has to read from data from disk every time a page is served - this moves data to redis which should speed things up significantly and reduce IO

2020-09-23 09:49 UTC, lotharsm approved these changes

2020-09-23 12:26 UTC, lotharsm commented
Thanks for your work on this, @Mataniko! Should we merge this so further development can continue in-tree?

2020-09-23 14:56 UTC, Mataniko commented
I'm planning to merge this alongside 2.2.0 release. This is a pretty major change so i'm trying to find breakage now.

2020-09-23 17:18 UTC, criezy commented
I only skimmed the changes, but it looks like this is great work!
My only worry is that I suspect the change to the screenshot names and paths will break the screenshots on the game pages on the wiki (as they get their screenshots from the website as far as I am aware).

2020-09-27 23:22 UTC, merged