Adding missing data on how to set up the site since data structure change
scummvm/scummvm-web pull request #136
Opened 2020-10-03 00:26 UTC by Thunderforge

It seems there were a few steps missing since the data structure change. I updated the readme to include them.

2020-10-03 01:07 UTC, Mataniko requested changes

2020-10-03 01:07 UTC, Mataniko commented on README.md
> +  * PHP Redis extension. Install via `pecl install redis` or `sudo apt install php-redis`
Optional - not needed for dev, recommended for prod

2020-10-03 01:07 UTC, Mataniko commented on README.md
> +* [Python & pip](https:˙//www.python.org/) (2.7.9+/3.4+)
remove single quote

2020-10-03 01:07 UTC, Mataniko commented on README.md
>  composer run
`composer start` now

2020-10-03 01:07 UTC, Mataniko commented on README.md
> +run `site-install` on the server.
"site update via the website admin page"

2020-10-03 01:11 UTC, Thunderforge commented on README.md
> +  * PHP Redis extension. Install via `pecl install redis` or `sudo apt install php-redis`
If I don't have YAML and Redis installed, I get this error when I try to run `composer install`:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-yaml * is missing from your system. Install or enable PHP's yaml extension.
  Problem 2
    - The requested PHP extension ext-redis * is missing from your system. Install or enable PHP's redis extension.
```

This would make it seem that there is indeed a need for it, even when running locally.

2020-10-03 01:13 UTC, Thunderforge commented on README.md
> +* [Python & pip](https:˙//www.python.org/) (2.7.9+/3.4+)
Fixed.

2020-10-03 01:15 UTC, Thunderforge commented on README.md
>  composer run
Fixed.

2020-10-03 01:15 UTC, Thunderforge commented on README.md
> +run `site-install` on the server.
Made a change. Did I understand what you were saying?

2020-10-03 02:53 UTC, Mataniko commented on README.md
> +  * PHP Redis extension. Install via `pecl install redis` or `sudo apt install php-redis`
Addressed in 3f2778d

2020-10-03 02:58 UTC, Mataniko commented on README.md
> +run `site-install` on the server.
no. there's no `site-install` command - it's simply a link in the admin page to update the site. Exact text is "ScummVM.org manual site update"

2020-10-03 02:59 UTC, Mataniko commented
Please squash the commits and reword the commit message to meet the guidelines

2020-10-05 02:03 UTC, Thunderforge commented on README.md
> +run `site-install` on the server.
Thanks, I understand now. Corrected.

2020-10-05 02:05 UTC, Thunderforge commented on README.md
> +  * PHP Redis extension. Install via `pecl install redis` or `sudo apt install php-redis`
@Mataniko With that commit, I am now able to build without `redis`. I've removed this from the Readme. Thanks.

2020-10-05 02:06 UTC, merged