IMAGES: Adding Dreamweb (German) screenshots
scummvm/scummvm-web pull request #239
Opened 2022-05-15 23:44 UTC by SupSuper

https://bugs.scummvm.org/ticket/12437

DreamWeb (CD/DOS/German)

2022-05-16 02:40 UTC, Thunderforge requested changes
[From the wiki](https://wiki.scummvm.org/index.php?title=Screenshots):

> For each game, we would like to have a small (say, between 2 and 5) number of screenshots which give users a good idea of what the game looks like to play.

This PR has too many screenshots. Can you cull it down to no more than 10?

2022-05-31 06:49 UTC, sev- commented
Not more than 2

2022-06-08 23:44 UTC, Thunderforge commented
Looks good. Thanks for this!

2022-06-08 23:44 UTC, Thunderforge approved these changes

2022-06-08 23:44 UTC, merged